ops: add `repository` entry to config
...as recommended here https://jekyll.github.io/github-metadata/configuration/

b/c the build in GitHub Actions is failing with this error:

```
Configuration file: /github/workspace/./_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /github/workspace/.
       Destination: /github/workspace/../jekyll_build
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Error processing value 'baseurl':
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.

```